# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'todo-service'
    static_configs:
      - targets: ['todo-service:8000']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']