name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

   
      - name: Install Auth Service dependencies
        run: |
          cd auth-service
          pip install -r requirements.txt
          pip install pytest

      - name: Run Auth Service tests
        run: |
          cd auth-service
          pytest

   
      - name: Install Todo Service dependencies
        run: |
          cd todo-service
          pip install -r requirements.txt
          pip install pytest

      - name: Run Todo Service tests
        run: |
          cd todo-service
          pytest

 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install

      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      
      - name: Build and Push Auth Service
        uses: docker/build-push-action@v2
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/system-integration-auth:latest

      - name: Build and Push Todo Service
        uses: docker/build-push-action@v2
        with:
          context: ./todo-service
          file: ./todo-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/system-integration-todo:latest

      - name: Build and Push Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/system-integration-gateway:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/system-integration-frontend:latest


  build-monitoring:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Prometheus
        uses: docker/build-push-action@v2
        with:
          context: ./monitoring/prometheus
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/system-integration-prometheus:latest

      - name: Build and Push Grafana
        uses: docker/build-push-action@v2
        with:
          context: ./monitoring/grafana
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/system-integration-grafana:latest